export const errCodes = {
  FIELDS_ARE_REQUIRED: 'FIELDS_ARE_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  REF_TOKEN_NOT_PRESENT: 'REF_TOKEN_NOT_PRESENT',
  NOT_VALID_REFRESH_TOKEN: 'NOT_VALID_REFRESH_TOKEN',
};
